run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
    # Exclude typecheck due to Kubernetes dependency version incompatibility
    # This is a known issue with golangci-lint and Kubernetes projects
    # The code compiles and tests pass successfully with go build and go test
    - linters:
        - typecheck
      text: "could not import k8s.io"
    - linters:
        - typecheck
      text: "undefined.*Get|Status|Create|Delete"
    # Exclude Ginkgo/Gomega test framework undefined symbols
    - linters:
        - typecheck
      text: "undefined.*(Describe|Context|It|BeforeEach|AfterEach|By|Expect|BeforeSuite|AfterSuite|RegisterFailHandler|RunSpecs|GinkgoWriter|Succeed|HaveOccurred|Fail|BeNil|Ordered|BeforeAll|AfterAll|ContainSubstring)"
    # Exclude webhook receiver method issues (r.Name, r.Namespace)
    - linters:
        - typecheck
      text: "r\\.(Name|Namespace) undefined"
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
