//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailableImageInfo) DeepCopyInto(out *AvailableImageInfo) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailableImageInfo.
func (in *AvailableImageInfo) DeepCopy() *AvailableImageInfo {
	if in == nil {
		return nil
	}
	out := new(AvailableImageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildConfigSpec) DeepCopyInto(out *BuildConfigSpec) {
	*out = *in
	if in.RequirementsSources != nil {
		in, out := &in.RequirementsSources, &out.RequirementsSources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StrategyConfig != nil {
		in, out := &in.StrategyConfig, &out.StrategyConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildConfigSpec.
func (in *BuildConfigSpec) DeepCopy() *BuildConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BuildConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildStatus) DeepCopyInto(out *BuildStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.AvailableImages != nil {
		in, out := &in.AvailableImages, &out.AvailableImages
		*out = make([]AvailableImageInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildStatus.
func (in *BuildStatus) DeepCopy() *BuildStatus {
	if in == nil {
		return nil
	}
	out := new(BuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellDiff) DeepCopyInto(out *CellDiff) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellDiff.
func (in *CellDiff) DeepCopy() *CellDiff {
	if in == nil {
		return nil
	}
	out := new(CellDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellResult) DeepCopyInto(out *CellResult) {
	*out = *in
	if in.ExecutionTime != nil {
		in, out := &in.ExecutionTime, &out.ExecutionTime
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellResult.
func (in *CellResult) DeepCopy() *CellResult {
	if in == nil {
		return nil
	}
	out := new(CellResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanEnvironmentCheckResult) DeepCopyInto(out *CleanEnvironmentCheckResult) {
	*out = *in
	if in.CRDsInstalled != nil {
		in, out := &in.CRDsInstalled, &out.CRDsInstalled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredLibraries != nil {
		in, out := &in.RequiredLibraries, &out.RequiredLibraries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanEnvironmentCheckResult.
func (in *CleanEnvironmentCheckResult) DeepCopy() *CleanEnvironmentCheckResult {
	if in == nil {
		return nil
	}
	out := new(CleanEnvironmentCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComparisonConfigSpec) DeepCopyInto(out *ComparisonConfigSpec) {
	*out = *in
	if in.FloatingPointTolerance != nil {
		in, out := &in.FloatingPointTolerance, &out.FloatingPointTolerance
		*out = new(string)
		**out = **in
	}
	if in.IgnoreTimestamps != nil {
		in, out := &in.IgnoreTimestamps, &out.IgnoreTimestamps
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreExecutionCount != nil {
		in, out := &in.IgnoreExecutionCount, &out.IgnoreExecutionCount
		*out = new(bool)
		**out = **in
	}
	if in.CustomTimestampPatterns != nil {
		in, out := &in.CustomTimestampPatterns, &out.CustomTimestampPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreOutputTypes != nil {
		in, out := &in.IgnoreOutputTypes, &out.IgnoreOutputTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComparisonConfigSpec.
func (in *ComparisonConfigSpec) DeepCopy() *ComparisonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ComparisonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComparisonResult) DeepCopyInto(out *ComparisonResult) {
	*out = *in
	if in.Diffs != nil {
		in, out := &in.Diffs, &out.Diffs
		*out = make([]CellDiff, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComparisonResult.
func (in *ComparisonResult) DeepCopy() *ComparisonResult {
	if in == nil {
		return nil
	}
	out := new(ComparisonResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapEnvSource) DeepCopyInto(out *ConfigMapEnvSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapEnvSource.
func (in *ConfigMapEnvSource) DeepCopy() *ConfigMapEnvSource {
	if in == nil {
		return nil
	}
	out := new(ConfigMapEnvSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPlatformSpec) DeepCopyInto(out *CustomPlatformSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPlatformSpec.
func (in *CustomPlatformSpec) DeepCopy() *CustomPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(CustomPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvFromSource) DeepCopyInto(out *EnvFromSource) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretEnvSource)
		**out = **in
	}
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapEnvSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvFromSource.
func (in *EnvFromSource) DeepCopy() *EnvFromSource {
	if in == nil {
		return nil
	}
	out := new(EnvFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(EnvVarSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVarSource) DeepCopyInto(out *EnvVarSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVarSource.
func (in *EnvVarSource) DeepCopy() *EnvVarSource {
	if in == nil {
		return nil
	}
	out := new(EnvVarSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExistingEnvironmentCheckResult) DeepCopyInto(out *ExistingEnvironmentCheckResult) {
	*out = *in
	if in.ModelsChecked != nil {
		in, out := &in.ModelsChecked, &out.ModelsChecked
		*out = make([]ModelCheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PredictionValidation != nil {
		in, out := &in.PredictionValidation, &out.PredictionValidation
		*out = new(PredictionValidationResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExistingEnvironmentCheckResult.
func (in *ExistingEnvironmentCheckResult) DeepCopy() *ExistingEnvironmentCheckResult {
	if in == nil {
		return nil
	}
	out := new(ExistingEnvironmentCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSpec) DeepCopyInto(out *GitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSpec.
func (in *GitSpec) DeepCopy() *GitSpec {
	if in == nil {
		return nil
	}
	out := new(GitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCheckResult) DeepCopyInto(out *ModelCheckResult) {
	*out = *in
	if in.ResourceStatus != nil {
		in, out := &in.ResourceStatus, &out.ResourceStatus
		*out = new(ModelResourceStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCheckResult.
func (in *ModelCheckResult) DeepCopy() *ModelCheckResult {
	if in == nil {
		return nil
	}
	out := new(ModelCheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelResourceStatus) DeepCopyInto(out *ModelResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelResourceStatus.
func (in *ModelResourceStatus) DeepCopy() *ModelResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ModelResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelValidationResult) DeepCopyInto(out *ModelValidationResult) {
	*out = *in
	if in.CleanEnvironmentCheck != nil {
		in, out := &in.CleanEnvironmentCheck, &out.CleanEnvironmentCheck
		*out = new(CleanEnvironmentCheckResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ExistingEnvironmentCheck != nil {
		in, out := &in.ExistingEnvironmentCheck, &out.ExistingEnvironmentCheck
		*out = new(ExistingEnvironmentCheckResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelValidationResult.
func (in *ModelValidationResult) DeepCopy() *ModelValidationResult {
	if in == nil {
		return nil
	}
	out := new(ModelValidationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelValidationSpec) DeepCopyInto(out *ModelValidationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TargetModels != nil {
		in, out := &in.TargetModels, &out.TargetModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PredictionValidation != nil {
		in, out := &in.PredictionValidation, &out.PredictionValidation
		*out = new(PredictionValidationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomPlatform != nil {
		in, out := &in.CustomPlatform, &out.CustomPlatform
		*out = new(CustomPlatformSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelValidationSpec.
func (in *ModelValidationSpec) DeepCopy() *ModelValidationSpec {
	if in == nil {
		return nil
	}
	out := new(ModelValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookSpec) DeepCopyInto(out *NotebookSpec) {
	*out = *in
	out.Git = in.Git
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookSpec.
func (in *NotebookSpec) DeepCopy() *NotebookSpec {
	if in == nil {
		return nil
	}
	out := new(NotebookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookValidationJob) DeepCopyInto(out *NotebookValidationJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookValidationJob.
func (in *NotebookValidationJob) DeepCopy() *NotebookValidationJob {
	if in == nil {
		return nil
	}
	out := new(NotebookValidationJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookValidationJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookValidationJobList) DeepCopyInto(out *NotebookValidationJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebookValidationJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookValidationJobList.
func (in *NotebookValidationJobList) DeepCopy() *NotebookValidationJobList {
	if in == nil {
		return nil
	}
	out := new(NotebookValidationJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookValidationJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookValidationJobSpec) DeepCopyInto(out *NotebookValidationJobSpec) {
	*out = *in
	out.Notebook = in.Notebook
	in.PodConfig.DeepCopyInto(&out.PodConfig)
	if in.GoldenNotebook != nil {
		in, out := &in.GoldenNotebook, &out.GoldenNotebook
		*out = new(NotebookSpec)
		**out = **in
	}
	if in.ComparisonConfig != nil {
		in, out := &in.ComparisonConfig, &out.ComparisonConfig
		*out = new(ComparisonConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelValidation != nil {
		in, out := &in.ModelValidation, &out.ModelValidation
		*out = new(ModelValidationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookValidationJobSpec.
func (in *NotebookValidationJobSpec) DeepCopy() *NotebookValidationJobSpec {
	if in == nil {
		return nil
	}
	out := new(NotebookValidationJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookValidationJobStatus) DeepCopyInto(out *NotebookValidationJobStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]CellResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRetryTime != nil {
		in, out := &in.LastRetryTime, &out.LastRetryTime
		*out = (*in).DeepCopy()
	}
	if in.ComparisonResult != nil {
		in, out := &in.ComparisonResult, &out.ComparisonResult
		*out = new(ComparisonResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ModelValidationResult != nil {
		in, out := &in.ModelValidationResult, &out.ModelValidationResult
		*out = new(ModelValidationResult)
		(*in).DeepCopyInto(*out)
	}
	if in.BuildStatus != nil {
		in, out := &in.BuildStatus, &out.BuildStatus
		*out = new(BuildStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookValidationJobStatus.
func (in *NotebookValidationJobStatus) DeepCopy() *NotebookValidationJobStatus {
	if in == nil {
		return nil
	}
	out := new(NotebookValidationJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConfigSpec) DeepCopyInto(out *PodConfigSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BuildConfig != nil {
		in, out := &in.BuildConfig, &out.BuildConfig
		*out = new(BuildConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConfigSpec.
func (in *PodConfigSpec) DeepCopy() *PodConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PodConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionValidationResult) DeepCopyInto(out *PredictionValidationResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionValidationResult.
func (in *PredictionValidationResult) DeepCopy() *PredictionValidationResult {
	if in == nil {
		return nil
	}
	out := new(PredictionValidationResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionValidationSpec) DeepCopyInto(out *PredictionValidationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionValidationSpec.
func (in *PredictionValidationSpec) DeepCopy() *PredictionValidationSpec {
	if in == nil {
		return nil
	}
	out := new(PredictionValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretEnvSource) DeepCopyInto(out *SecretEnvSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretEnvSource.
func (in *SecretEnvSource) DeepCopy() *SecretEnvSource {
	if in == nil {
		return nil
	}
	out := new(SecretEnvSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}
